from dataclasses import asdict
from math import isfinite
from pathlib import Path
from typing import Any
import json
import re

import pandas as pd

from etf_momentum_backtest.backtest import BacktestResult
from etf_momentum_backtest.benchmarks import BenchmarkResults
from etf_momentum_backtest.config import BacktestConfig
from etf_momentum_backtest.metrics import PerformanceMetrics


def make_path_safe_name(value: str) -> str:
    """Convert a display name into a filesystem-safe name."""

    normalized = value.strip().replace("&", "and")

    normalized = re.sub(
        r"[^A-Za-z0-9_-]+",
        "_",
        normalized,
    )

    return normalized.strip("_")


def format_number_key(value: float) -> str:
    """Format a number compactly for use in a run name."""

    if value.is_integer():
        return str(int(value))

    return format(value, "g").replace(".", "p")


def build_run_name(
    config: BacktestConfig,
) -> str:
    """Build a deterministic name for one backtest configuration."""

    ticker_key = "_".join(config.tickers)
    start_key = config.start_date.replace("-", "")

    end_key = (
        config.end_date.replace("-", "") if config.end_date is not None else "latest"
    )

    cost_bps = config.transaction_cost_rate * 10_000

    cost_key = format_number_key(cost_bps)

    return (
        f"{ticker_key}_"
        f"{start_key}_{end_key}_"
        f"lb{config.lookback_days}_"
        f"top{config.top_k}_"
        f"cost{cost_key}bps"
    )


def to_json_compatible(
    value: Any,
) -> Any:
    """Convert project values into JSON-compatible objects."""

    if isinstance(value, pd.Timestamp):
        return value.isoformat()

    if isinstance(value, Path):
        return str(value)

    if isinstance(value, tuple):
        return [to_json_compatible(item) for item in value]

    if isinstance(value, list):
        return [to_json_compatible(item) for item in value]

    if isinstance(value, dict):
        return {str(key): to_json_compatible(item) for key, item in value.items()}

    if isinstance(value, float):
        if not isfinite(value):
            return None

        return value

    return value


def write_json(
    data: dict[str, Any],
    path: Path,
) -> None:
    """Write a dictionary as formatted UTF-8 JSON."""

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    serialized = to_json_compatible(data)

    with path.open(
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            serialized,
            file,
            indent=2,
            ensure_ascii=False,
        )

        file.write("\n")


def save_config(
    config: BacktestConfig,
    path: Path,
) -> None:
    """Save the resolved backtest configuration."""

    write_json(
        data=asdict(config),
        path=path,
    )


def save_metrics(
    metrics: PerformanceMetrics,
    path: Path,
) -> None:
    """Save one portfolio's performance metrics."""

    write_json(
        data=asdict(metrics),
        path=path,
    )


def save_backtest_result(
    result: BacktestResult,
    output_dir: Path,
) -> None:
    """Save every time series generated by one backtest."""

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    result.portfolio_value.to_csv(
        output_dir / "portfolio_value.csv",
        index_label="date",
    )

    result.daily_returns.to_csv(
        output_dir / "daily_returns.csv",
        index_label="date",
    )

    result.actual_weights.to_csv(
        output_dir / "actual_weights.csv",
        index_label="date",
    )

    result.cash_balance.to_csv(
        output_dir / "cash_balance.csv",
        index_label="date",
    )

    result.turnover.to_csv(
        output_dir / "turnover.csv",
        index_label="date",
    )

    result.transaction_costs.to_csv(
        output_dir / "transaction_costs.csv",
        index_label="date",
    )

    result.execution_targets.to_csv(
        output_dir / "execution_targets.csv",
        index_label="execution_date",
    )


def build_performance_comparison(
    strategy_metrics: PerformanceMetrics,
    benchmark_metrics: dict[
        str,
        PerformanceMetrics,
    ],
) -> pd.DataFrame:
    """Build a strategy-versus-benchmark comparison table."""

    all_metrics = {
        "Momentum Strategy": strategy_metrics,
        **benchmark_metrics,
    }

    rows: dict[str, dict[str, float | int]] = {}

    for name, metrics in all_metrics.items():
        rows[name] = {
            "final_value": metrics.final_value,
            "total_return": metrics.total_return,
            "cagr": metrics.cagr,
            "annualized_volatility": (metrics.annualized_volatility),
            "sharpe_ratio": metrics.sharpe_ratio,
            "sortino_ratio": metrics.sortino_ratio,
            "max_drawdown": metrics.max_drawdown,
            "calmar_ratio": metrics.calmar_ratio,
            "total_turnover": metrics.total_turnover,
            "annualized_turnover": (metrics.annualized_turnover),
            "number_of_rebalances": (metrics.number_of_rebalances),
            "total_transaction_costs": (metrics.total_transaction_costs),
        }

    comparison = pd.DataFrame.from_dict(
        rows,
        orient="index",
    )

    comparison.index.name = "portfolio"

    return comparison


def save_analysis_outputs(
    config: BacktestConfig,
    strategy_target_weights: pd.DataFrame,
    strategy_result: BacktestResult,
    strategy_metrics: PerformanceMetrics,
    benchmark_results: BenchmarkResults,
    benchmark_metrics: dict[
        str,
        PerformanceMetrics,
    ],
) -> Path:
    """Save all strategy and benchmark outputs for one run."""

    run_dir = config.results_dir / build_run_name(config)

    run_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    save_config(
        config=config,
        path=run_dir / "config.json",
    )

    strategy_target_weights.to_csv(
        run_dir / "target_weights.csv",
        index_label="signal_date",
    )

    strategy_dir = run_dir / "strategy"

    save_backtest_result(
        result=strategy_result,
        output_dir=strategy_dir,
    )

    save_metrics(
        metrics=strategy_metrics,
        path=strategy_dir / "metrics.json",
    )

    benchmark_result_map = benchmark_results.as_dict()

    if set(benchmark_result_map) != set(benchmark_metrics):
        raise ValueError("Benchmark result names do not match benchmark metric names.")

    benchmarks_dir = run_dir / "benchmarks"

    for name, result in benchmark_result_map.items():
        benchmark_dir = benchmarks_dir / make_path_safe_name(name)

        save_backtest_result(
            result=result,
            output_dir=benchmark_dir,
        )

        save_metrics(
            metrics=benchmark_metrics[name],
            path=benchmark_dir / "metrics.json",
        )

    comparison = build_performance_comparison(
        strategy_metrics=strategy_metrics,
        benchmark_metrics=benchmark_metrics,
    )

    comparison.to_csv(
        run_dir / "performance_comparison.csv",
    )

    return run_dir
